/* ============================================================
   SHARED CATALOG — single source of truth for the video catalog.
   Loaded at runtime by every page (viewer / creator / manager / index)
   via <script src="../catalog.js"></script> BEFORE the page's own script.

   Defines globals used across all pages: MEDIA_BASE, mediaUrl(), DATA.
   Edit the catalog HERE ONLY — no more 4-file sync. After editing, upload
   catalog.js to Bunny storage and purge the Pull Zone cache (see CLAUDE.md).
   ============================================================ */

const MEDIA_BASE = "https://streamhub-media.b-cdn.net";

/* HTML-escape a value for safe interpolation into innerHTML template strings.
   Use for ALL dynamic/user/catalog text rendered via innerHTML (titles, comments,
   names, search input, etc.) to prevent stored/reflected XSS. Returns "" for
   null/undefined so missing fields render blank instead of "undefined". */
function esc(s){
  if(s === null || s === undefined) return "";
  return String(s)
    .replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")
    .replace(/"/g,"&quot;").replace(/'/g,"&#39;");
}

/* ---------- shared helpers (identical across all pages; defined once here) ---------- */

/* Look up a creator's display name by id. */
function creatorName(id){ const c = DATA.creators.find(x=>x.id===id); return c?c.name:"Unknown"; }

/* Format a number compactly: 1.2M / 3.4K / 567. */
function fmt(n){ return n>=1000000 ? (n/1000000).toFixed(1)+"M" : n>=1000 ? (n/1000).toFixed(1)+"K" : ""+n; }

/* Transient toast notification. Expects a #toast element on the page. */
let _toastTimer;
function toast(msg){
  const t=document.getElementById("toast"); if(!t) return;
  t.textContent=msg; t.classList.add("show");
  clearTimeout(_toastTimer); _toastTimer=setTimeout(()=>t.classList.remove("show"),2400);
}

/* Rewrite a "../media/x.mp4" path to the CDN when MEDIA_BASE is set */
function mediaUrl(src){
  if(!src) return src;
  if(/^https?:\/\//.test(src) || src.startsWith("blob:") || src.startsWith("data:")) return src;
  if(!MEDIA_BASE) return src;                       // local mode, keep relative path
  // strip leading "../media/" (or "media/") then keep the rest of the path,
  // URL-encoding each segment so spaces/subfolders work.
  const rel = src.replace(/^(\.\.\/)?media\//, "");
  const path = rel.split("/").map(encodeURIComponent).join("/");
  return MEDIA_BASE.replace(/\/$/,"") + "/" + path;
}

const DATA = {
  user: { id:"u1", name:"Alex", handle:"@alex", avatar:"A", subscriptions:42, role:"viewer" },

  creators: [
    { id:"c1", name:"House Originals", handle:"@house", subs:1240000, verified:true },
    { id:"c2", name:"Maya Chen",       handle:"@maya",  subs:84000,   verified:true },
    { id:"c3", name:"DevTalks",        handle:"@devtalks", subs:31000, verified:false },
    { id:"c4", name:"Alex",            handle:"@alex",  subs:1240,     verified:false },
  ],

  categories: ["POV","Big Ass","Cumshot","Squirt","Big","Beauty","AI","Boy Girl","Girl Girl","Boy Boy","Blowjob","Compilation","Facial","Threesome","Blond","18-25","Amateur","Asian","Babe","Anal"],

  videos: [
    { id:1, title:"Blonde Office Twerk", creator:"c3", type:"ugc", category:"Blond", views:14312, likes:222, dislikes:5, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-04", src:"../media/Blonde Office Twerk video by ttt-ai on DeviantArt.mp4", status:"published", flagged:false },
    { id:2, title:"HUge TITS PINK00005", creator:"c1", type:"original", category:"Big", views:12033, likes:136, dislikes:16, comments:3, favorites:0, duration:"0:10", uploaded:"2026-04-03", src:"../media/HUge TITS PINK00005.mp4", status:"published", flagged:false },
    { id:3, title:"Naked surfer G2159", creator:"c4", type:"ugc", category:"Boy Boy", views:10222, likes:136, dislikes:10, comments:1, favorites:0, duration:"0:10", uploaded:"2026-06-21", src:"../media/Naked surfer -G2159 video by The-Satin-Pause on DeviantArt.mp4", status:"published", flagged:false },
    { id:4, title:"Perfect Pussy Twerk", creator:"c1", type:"original", category:"Babe", views:10533, likes:264, dislikes:5, comments:1, favorites:0, duration:"0:10", uploaded:"2026-01-18", src:"../media/Perfect Pussy Twerk .mp4", status:"published", flagged:false },
    { id:5, title:"Perfect doggy cumming00001", creator:"c3", type:"ugc", category:"Anal", views:11208, likes:119, dislikes:10, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-18", src:"../media/Perfect doggy cumming00001.mp4", status:"published", flagged:false },
    { id:6, title:"Sexy by SexyGirls2", creator:"c2", type:"ugc", category:"Asian", views:14589, likes:247, dislikes:13, comments:2, favorites:0, duration:"0:10", uploaded:"2026-01-18", src:"../media/Sexy by SexyGirls2 on DeviantArt (4).mp4", status:"published", flagged:false },
    { id:7, title:"Solo beach walk G2630", creator:"c1", type:"original", category:"POV", views:10478, likes:257, dislikes:4, comments:3, favorites:0, duration:"0:10", uploaded:"2026-03-15", src:"../media/Solo beach walk -G2630 video by The-Satin-Pause on DeviantArt (7).mp4", status:"published", flagged:false },
    { id:8, title:"Solo beach walk", creator:"c4", type:"ugc", category:"Amateur", views:10508, likes:220, dislikes:5, comments:1, favorites:0, duration:"0:10", uploaded:"2026-01-19", src:"../media/Solo beach walk.mp4", status:"published", flagged:false },
    { id:9, title:"Sunscreen G2718", creator:"c4", type:"ugc", category:"Blowjob", views:10520, likes:107, dislikes:4, comments:4, favorites:0, duration:"0:10", uploaded:"2026-01-04", src:"../media/Sunscreen -G2718 video by The-Satin-Pause on DeviantArt.mp4", status:"published", flagged:false },
    { id:10, title:"Surrender to nature G2538", creator:"c2", type:"ugc", category:"Amateur", views:13332, likes:250, dislikes:14, comments:3, favorites:0, duration:"0:10", uploaded:"2026-01-22", src:"../media/Surrender to nature -G2538 video by The-Satin-Pause on DeviantArt.mp4", status:"published", flagged:true },
    { id:11, title:"All", creator:"c3", type:"ugc", category:"POV", views:12415, likes:188, dislikes:9, comments:3, favorites:0, duration:"0:10", uploaded:"2026-05-26", src:"../media/all.mp4", status:"published", flagged:false },
    { id:12, title:"Amazing 18", creator:"c1", type:"original", category:"18-25", views:12576, likes:153, dislikes:13, comments:0, favorites:0, duration:"0:10", uploaded:"2026-06-23", src:"../media/amazing 18.mp4", status:"published", flagged:false },
    { id:13, title:"Amazing big natural", creator:"c4", type:"ugc", category:"Big", views:12949, likes:234, dislikes:2, comments:0, favorites:0, duration:"0:10", uploaded:"2026-04-12", src:"../media/amazing big natural.mp4", status:"published", flagged:false },
    { id:14, title:"Anazing girls on the beach", creator:"c1", type:"original", category:"Girl Girl", views:13225, likes:118, dislikes:4, comments:1, favorites:0, duration:"0:10", uploaded:"2026-06-08", src:"../media/anazing girls on the beach.mp4", status:"published", flagged:false },
    { id:15, title:"Beauty girl", creator:"c4", type:"ugc", category:"Beauty", views:14843, likes:137, dislikes:17, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-05", src:"../media/beauty girl.mp4", status:"published", flagged:false },
    { id:16, title:"Big natural", creator:"c3", type:"ugc", category:"Big", views:10979, likes:183, dislikes:19, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-03", src:"../media/big natural.mp4", status:"published", flagged:false },
    { id:17, title:"Blond girl having fun", creator:"c2", type:"ugc", category:"Blond", views:12997, likes:284, dislikes:4, comments:4, favorites:0, duration:"0:10", uploaded:"2026-02-09", src:"../media/blond girl having fun.mp4", status:"published", flagged:false },
    { id:18, title:"Blond", creator:"c2", type:"ugc", category:"Blond", views:12441, likes:188, dislikes:5, comments:2, favorites:0, duration:"0:10", uploaded:"2026-02-23", src:"../media/blond.mp4", status:"published", flagged:false },
    { id:19, title:"Blondy ai", creator:"c1", type:"original", category:"Blond", views:11521, likes:164, dislikes:9, comments:3, favorites:0, duration:"0:10", uploaded:"2026-04-13", src:"../media/blondy ai.mp4", status:"published", flagged:false },
    { id:20, title:"Comming gitls", creator:"c4", type:"ugc", category:"Amateur", views:13890, likes:146, dislikes:19, comments:0, favorites:0, duration:"0:10", uploaded:"2026-02-15", src:"../media/comming gitls.mp4", status:"published", flagged:false },
    { id:21, title:"AI Generated Clip (1)", creator:"c3", type:"ugc", category:"AI", views:10390, likes:157, dislikes:7, comments:4, favorites:0, duration:"0:10", uploaded:"2026-02-18", src:"../media/grok-video-356eddc7-87b2-4217-9418-ddc9ff6d900a (1).mp4", status:"published", flagged:true },
    { id:22, title:"AI Generated Clip (12)", creator:"c3", type:"ugc", category:"AI", views:11067, likes:109, dislikes:8, comments:4, favorites:0, duration:"0:10", uploaded:"2026-04-05", src:"../media/grok-video-db383327-45a9-4339-a5a5-22973570fb5c (12).mp4", status:"published", flagged:false },
    { id:23, title:"Redhead", creator:"c3", type:"ugc", category:"Boy Girl", views:14855, likes:190, dislikes:7, comments:0, favorites:0, duration:"0:10", uploaded:"2026-04-15", src:"../media/redhead.mp4", status:"published", flagged:false },
    { id:24, title:"Robo sex ai", creator:"c3", type:"ugc", category:"AI", views:10632, likes:150, dislikes:17, comments:2, favorites:0, duration:"0:10", uploaded:"2026-04-27", src:"../media/robo-sex ai.mp4", status:"published", flagged:false },
    { id:25, title:"Robo sex", creator:"c1", type:"original", category:"AI", views:12736, likes:289, dislikes:2, comments:2, favorites:0, duration:"0:10", uploaded:"2026-02-23", src:"../media/robo-sex.mp4", status:"published", flagged:false },
    { id:26, title:"Sexy milf", creator:"c1", type:"original", category:"Babe", views:14478, likes:180, dislikes:11, comments:2, favorites:0, duration:"0:10", uploaded:"2026-05-12", src:"../media/sexy milf.mp4", status:"published", flagged:false },
    { id:27, title:"She is comming", creator:"c3", type:"ugc", category:"Amateur", views:10944, likes:118, dislikes:15, comments:2, favorites:0, duration:"0:10", uploaded:"2026-06-08", src:"../media/she is comming.mp4", status:"published", flagged:false },
    { id:28, title:"Suger daddy", creator:"c2", type:"ugc", category:"Babe", views:14907, likes:262, dislikes:4, comments:1, favorites:0, duration:"0:10", uploaded:"2026-05-16", src:"../media/suger-daddy.mp4", status:"published", flagged:false },
    { id:29, title:"The best sexy cyber", creator:"c1", type:"original", category:"AI", views:10800, likes:236, dislikes:5, comments:2, favorites:0, duration:"0:10", uploaded:"2026-02-23", src:"../media/the best sexy cyber.mp4", status:"published", flagged:false },
    { id:30, title:"Threesome girls", creator:"c3", type:"ugc", category:"Threesome", views:12257, likes:136, dislikes:11, comments:2, favorites:0, duration:"0:10", uploaded:"2026-01-08", src:"../media/threesome girls.mp4", status:"published", flagged:true },
    { id:31, title:"Threesome girls2", creator:"c4", type:"ugc", category:"Threesome", views:11349, likes:198, dislikes:11, comments:4, favorites:0, duration:"0:10", uploaded:"2026-05-27", src:"../media/threesome girls2.mp4", status:"published", flagged:true },
    { id:32, title:"Cumshot Mix 01", creator:"c4", type:"ugc", category:"Blowjob", categories:["Blowjob"], views:11419, likes:271, dislikes:6, comments:4, favorites:0, duration:"0:10", uploaded:"2026-02-02", src:"../media/comshot compilation00001.mp4", tags:["Deepthroat", "Cumshot", "Big Tits"], status:"published", flagged:true },
    { id:33, title:"Best Cumshots 02", creator:"c1", type:"ugc", category:"Blowjob", categories:["Blowjob"], views:12337, likes:274, dislikes:5, comments:4, favorites:0, duration:"0:10", uploaded:"2026-01-19", src:"../media/comshot compilation00002.mp4", tags:["Blowjob", "Deepthroat", "Cumshot"], status:"published", flagged:false },
    { id:34, title:"Cum Compilation 03", creator:"c2", type:"ugc", category:"Cumshot", categories:["Cumshot"], views:14064, likes:223, dislikes:6, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-18", src:"../media/comshot compilation00003.mp4", tags:["Handjob", "Facial", "Big Tits"], status:"published", flagged:false },
    { id:35, title:"Best Cumshots 04", creator:"c4", type:"ugc", category:"Amateur", categories:["Amateur"], views:11765, likes:103, dislikes:3, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-07", src:"../media/comshot compilation00004.mp4", tags:["Compilation", "POV", "Cumshot"], status:"published", flagged:false },
    { id:36, title:"Cumshot Mix 05", creator:"c3", type:"ugc", category:"Facial", categories:["Facial"], views:12453, likes:238, dislikes:5, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-10", src:"../media/comshot compilation00005.mp4", tags:["Big Tits", "POV", "Facial"], status:"published", flagged:false },
    { id:37, title:"Cum Tribute 06", creator:"c1", type:"ugc", category:"Compilation", categories:["Compilation"], views:14405, likes:119, dislikes:8, comments:1, favorites:0, duration:"0:10", uploaded:"2026-04-14", src:"../media/comshot compilation00006.mp4", tags:["Blowjob", "Handjob", "Amateur"], status:"published", flagged:true },
    { id:38, title:"Hot Load Comp 07", creator:"c1", type:"ugc", category:"Amateur", categories:["Amateur"], views:13158, likes:116, dislikes:2, comments:0, favorites:0, duration:"0:10", uploaded:"2026-01-09", src:"../media/comshot compilation00007.mp4", tags:["POV", "Handjob", "Big Tits"], status:"published", flagged:false },
    { id:39, title:"Cumshot Compilation 08", creator:"c1", type:"ugc", category:"POV", categories:["POV"], views:14633, likes:132, dislikes:4, comments:0, favorites:0, duration:"0:10", uploaded:"2026-04-12", src:"../media/comshot compilation00008.mp4", tags:["Amateur", "Big Tits", "Facial"], status:"published", flagged:false },
    { id:40, title:"Cum Tribute 09", creator:"c3", type:"ugc", category:"Cumshot", categories:["Cumshot"], views:11027, likes:122, dislikes:10, comments:0, favorites:0, duration:"0:10", uploaded:"2026-02-15", src:"../media/comshot compilation00009.mp4", tags:["Compilation", "Amateur", "Blowjob"], status:"published", flagged:false },
    { id:41, title:"Facial Finale 10", creator:"c2", type:"ugc", category:"Facial", categories:["Facial"], views:12552, likes:229, dislikes:4, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-03", src:"../media/comshot compilation00010.mp4", tags:["Handjob", "Amateur", "POV"], status:"published", flagged:false },
    { id:42, title:"Cum Compilation 11", creator:"c2", type:"ugc", category:"Cumshot", categories:["Cumshot"], views:10984, likes:148, dislikes:9, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-20", src:"../media/comshot compilation00011.mp4", tags:["Big Tits", "Facial", "Handjob"], status:"published", flagged:false },
    { id:43, title:"Hot Load Comp 12", creator:"c1", type:"ugc", category:"Amateur", categories:["Amateur"], views:12276, likes:266, dislikes:4, comments:3, favorites:0, duration:"0:10", uploaded:"2026-01-16", src:"../media/comshot compilation00012.mp4", tags:["Cumshot", "Big Tits", "Deepthroat"], status:"published", flagged:false },
    { id:44, title:"Cum Compilation 13", creator:"c1", type:"ugc", category:"Cumshot", categories:["Cumshot"], views:14606, likes:287, dislikes:13, comments:0, favorites:0, duration:"0:10", uploaded:"2026-01-19", src:"../media/comshot compilation00013.mp4", tags:["Compilation", "Big Tits", "Blowjob"], status:"published", flagged:false },
    { id:45, title:"Cumshot Mix 14", creator:"c1", type:"ugc", category:"Amateur", categories:["Amateur"], views:11125, likes:170, dislikes:9, comments:2, favorites:0, duration:"0:10", uploaded:"2026-03-20", src:"../media/comshot compilation00014.mp4", tags:["Cumshot", "Blowjob", "Deepthroat"], status:"published", flagged:false },
    { id:46, title:"Best Cumshots 15", creator:"c2", type:"ugc", category:"Facial", categories:["Facial"], views:11441, likes:153, dislikes:17, comments:2, favorites:0, duration:"0:10", uploaded:"2026-06-09", src:"../media/comshot compilation00015.mp4", tags:["Big Tits", "Handjob", "Compilation"], status:"published", flagged:false },
    { id:47, title:"Hot Load Comp 16", creator:"c3", type:"ugc", category:"Cumshot", categories:["Cumshot"], views:13510, likes:247, dislikes:12, comments:2, favorites:0, duration:"0:10", uploaded:"2026-06-28", src:"../media/comshot compilation00017.mp4", tags:["Compilation", "POV", "Blowjob"], status:"published", flagged:true },
    { id:48, title:"Hot Load Comp 17", creator:"c2", type:"ugc", category:"Compilation", categories:["Compilation"], views:14570, likes:281, dislikes:11, comments:2, favorites:0, duration:"0:10", uploaded:"2026-06-08", src:"../media/comshot compilation00019.mp4", tags:["Facial", "POV", "Deepthroat"], status:"published", flagged:false },
    { id:49, title:"Cum Compilation 18", creator:"c3", type:"ugc", category:"Facial", categories:["Facial"], views:14200, likes:195, dislikes:3, comments:0, favorites:0, duration:"0:10", uploaded:"2026-03-16", src:"../media/comshot compilation00020.mp4", tags:["Compilation", "Handjob", "Amateur"], status:"published", flagged:false },
    { id:50, title:"Cum Tribute 19", creator:"c1", type:"ugc", category:"POV", categories:["POV"], views:11127, likes:142, dislikes:8, comments:1, favorites:0, duration:"0:10", uploaded:"2026-03-07", src:"../media/comshot compilation00022.mp4", tags:["POV", "Handjob", "Cumshot"], status:"published", flagged:false },
    { id:51, title:"Cum Tribute 20", creator:"c3", type:"ugc", category:"POV", categories:["POV"], views:11899, likes:175, dislikes:19, comments:3, favorites:0, duration:"0:10", uploaded:"2026-02-14", src:"../media/comshot compilation00023.mp4", tags:["POV", "Blowjob", "Deepthroat"], status:"published", flagged:false },
    { id:52, title:"Best Cumshots 21", creator:"c4", type:"ugc", category:"POV", categories:["POV"], views:14619, likes:117, dislikes:2, comments:1, favorites:0, duration:"0:10", uploaded:"2026-01-05", src:"../media/comshot compilation00024.mp4", tags:["Deepthroat", "Big Tits", "Compilation"], status:"published", flagged:false },
    { id:53, title:"Facial Finale 22", creator:"c2", type:"ugc", category:"Amateur", categories:["Amateur"], views:14559, likes:180, dislikes:5, comments:0, favorites:0, duration:"0:10", uploaded:"2026-06-21", src:"../media/comshot compilation00025.mp4", tags:["Big Tits", "POV", "Blowjob"], status:"published", flagged:false },
    { id:54, title:"Ass Appreciation", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:10220, likes:269, dislikes:7, comments:4, favorites:0, duration:"0:10", uploaded:"2026-01-25", src:"../media/Amazing Ass1.mp4", tags:["Doggy", "POV", "Big Ass"], status:"published", flagged:false },
    { id:55, title:"Twerk Queen", creator:"c1", type:"ugc", category:"POV", categories:["POV"], views:14789, likes:127, dislikes:13, comments:3, favorites:0, duration:"0:10", uploaded:"2026-06-09", src:"../media/Amazing Ass2.mp4", tags:["Booty", "Doggy", "Curvy"], status:"published", flagged:false },
    { id:56, title:"Perfect Curves", creator:"c1", type:"ugc", category:"Amateur", categories:["Amateur"], views:10884, likes:150, dislikes:19, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-25", src:"../media/Amazing Ass3.mp4", tags:["Twerk", "Curvy", "Thick"], status:"published", flagged:false },
    { id:57, title:"Booty Bounce", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:11701, likes:211, dislikes:20, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-02", src:"../media/Amazing Ass4.mp4", tags:["Twerk", "Thick", "Big Ass"], status:"published", flagged:false },
    { id:58, title:"Big Booty Babe", creator:"c4", type:"ugc", category:"POV", categories:["POV"], views:12166, likes:207, dislikes:16, comments:2, favorites:0, duration:"0:10", uploaded:"2026-01-10", src:"../media/Amazing Ass5.mp4", tags:["Thick", "POV", "Twerk"], status:"published", flagged:false },
    { id:59, title:"Booty Heaven", creator:"c4", type:"ugc", category:"Amateur", categories:["Amateur"], views:14037, likes:228, dislikes:12, comments:3, favorites:0, duration:"0:10", uploaded:"2026-02-22", src:"../media/Amazing Ass6.mp4", tags:["POV", "Amateur", "Doggy"], status:"published", flagged:false },
    { id:60, title:"Bubble Butt", creator:"c1", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12885, likes:228, dislikes:3, comments:0, favorites:0, duration:"0:10", uploaded:"2026-04-14", src:"../media/Amazing Ass7.mp4", tags:["Doggy", "Booty", "Curvy"], status:"published", flagged:false },
    { id:61, title:"Backshots", creator:"c3", type:"ugc", category:"POV", categories:["POV"], views:13101, likes:156, dislikes:5, comments:0, favorites:0, duration:"0:10", uploaded:"2026-01-05", src:"../media/Amazing Ass8.mp4", tags:["Twerk", "Doggy", "Big Ass"], status:"published", flagged:false },
    { id:62, title:"Perfect Booty", creator:"c1", type:"ugc", category:"Amateur", categories:["Amateur"], views:14806, likes:181, dislikes:18, comments:0, favorites:0, duration:"0:10", uploaded:"2026-02-19", src:"../media/Amazing Ass9.mp4", tags:["Big Ass", "Curvy", "Thick"], status:"published", flagged:false },
    { id:63, title:"Phat Ass Babe", creator:"c2", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:14964, likes:142, dislikes:12, comments:4, favorites:0, duration:"0:10", uploaded:"2026-02-28", src:"../media/Amazing Ass10.mp4", tags:["Curvy", "Doggy", "Twerk"], status:"published", flagged:false },
    { id:64, title:"Peachy Keen", creator:"c2", type:"ugc", category:"POV", categories:["POV"], views:10225, likes:245, dislikes:12, comments:1, favorites:0, duration:"0:10", uploaded:"2026-06-21", src:"../media/Amazing Ass11.mp4", tags:["Twerk", "Booty", "Thick"], status:"published", flagged:false },
    { id:65, title:"Amazing Ass POV", creator:"c2", type:"ugc", category:"Amateur", categories:["Amateur"], views:11005, likes:268, dislikes:8, comments:0, favorites:0, duration:"0:10", uploaded:"2026-01-17", src:"../media/Amazing Ass12.mp4", tags:["Thick", "Babe", "Twerk"], status:"published", flagged:false },
    { id:66, title:"Thick & Juicy", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:13326, likes:202, dislikes:10, comments:1, favorites:0, duration:"0:10", uploaded:"2026-06-03", src:"../media/Amazing Ass13.mp4", tags:["Thick", "Twerk", "Booty"], status:"published", flagged:false },
    { id:67, title:"Ass Worship", creator:"c2", type:"ugc", category:"POV", categories:["POV"], views:11868, likes:232, dislikes:14, comments:0, favorites:0, duration:"0:10", uploaded:"2026-01-09", src:"../media/Amazing Ass14.mp4", tags:["Doggy", "POV", "Amateur"], status:"published", flagged:false },
    { id:68, title:"Big Ass Compilation", creator:"c4", type:"ugc", category:"Amateur", categories:["Amateur"], views:13127, likes:146, dislikes:11, comments:1, favorites:0, duration:"0:10", uploaded:"2026-01-12", src:"../media/Amazing Ass15.mp4", tags:["Big Ass", "Doggy", "POV"], status:"published", flagged:false },
    { id:69, title:"Booty Call", creator:"c1", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12960, likes:207, dislikes:19, comments:2, favorites:0, duration:"0:10", uploaded:"2026-06-10", src:"../media/Amazing Ass18.mp4", tags:["Curvy", "Amateur", "Twerk"], status:"published", flagged:false },
    { id:70, title:"Thicc Goddess", creator:"c1", type:"ugc", category:"POV", categories:["POV"], views:11669, likes:270, dislikes:4, comments:0, favorites:0, duration:"0:10", uploaded:"2026-04-18", src:"../media/Amazing Ass19.mp4", tags:["POV", "Babe", "Big Ass"], status:"published", flagged:false },
    { id:71, title:"Ass-tastic", creator:"c1", type:"ugc", category:"Amateur", categories:["Amateur"], views:10866, likes:229, dislikes:10, comments:3, favorites:0, duration:"0:10", uploaded:"2026-01-28", src:"../media/Amazing Ass20.mp4", tags:["Amateur", "Curvy", "Doggy"], status:"published", flagged:false },
    { id:72, title:"Booty Goals", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:14906, likes:176, dislikes:9, comments:0, favorites:0, duration:"0:10", uploaded:"2026-06-04", src:"../media/Amazing Ass21.mp4", tags:["Thick", "Doggy", "Twerk"], status:"published", flagged:false },
    { id:73, title:"Round & Perfect", creator:"c1", type:"ugc", category:"POV", categories:["POV"], views:11686, likes:213, dislikes:5, comments:4, favorites:0, duration:"0:10", uploaded:"2026-01-17", src:"../media/Amazing Ass22.mp4", tags:["Curvy", "Thick", "Doggy"], status:"published", flagged:false },
    { id:74, title:"Curvy Cutie", creator:"c3", type:"ugc", category:"Amateur", categories:["Amateur"], views:10475, likes:158, dislikes:13, comments:3, favorites:0, duration:"0:10", uploaded:"2026-05-22", src:"../media/Amazing Ass23.mp4", tags:["Twerk", "POV", "Booty"], status:"published", flagged:false },
    { id:75, title:"Booty Paradise", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12370, likes:259, dislikes:10, comments:4, favorites:0, duration:"0:10", uploaded:"2026-02-25", src:"../media/Amazing Ass24.mp4", tags:["Big Ass", "Curvy", "Amateur"], status:"published", flagged:false },
    { id:76, title:"Big Booty Energy", creator:"c3", type:"ugc", category:"POV", categories:["POV"], views:12030, likes:156, dislikes:2, comments:3, favorites:0, duration:"0:10", uploaded:"2026-02-07", src:"../media/Amazing Ass25.mp4", tags:["Babe", "Booty", "Amateur"], status:"published", flagged:false },
    { id:77, title:"Thick Thighs", creator:"c4", type:"ugc", category:"Amateur", categories:["Amateur"], views:12659, likes:265, dislikes:2, comments:0, favorites:0, duration:"0:10", uploaded:"2026-03-27", src:"../media/Amazing Ass26.mp4", tags:["Booty", "Amateur", "POV"], status:"published", flagged:false },
    { id:78, title:"Dat Ass", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:14784, likes:111, dislikes:14, comments:3, favorites:0, duration:"0:10", uploaded:"2026-06-11", src:"../media/Amazing Ass27.mp4", tags:["Babe", "Twerk", "POV"], status:"published", flagged:false },
    { id:79, title:"Juicy Peach", creator:"c1", type:"ugc", category:"POV", categories:["POV"], views:14441, likes:211, dislikes:18, comments:2, favorites:0, duration:"0:10", uploaded:"2026-05-12", src:"../media/Amazing Ass29.mp4", tags:["Curvy", "POV", "Thick"], status:"published", flagged:false },
    { id:80, title:"Play With Fun Bags", creator:"c3", type:"ugc", category:"Babe", categories:["Babe"], views:13792, likes:105, dislikes:15, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-05", src:"../media/new bunny uplode/Play with Fun Bags by HeavenlyFlesh on DeviantArt.mp4", tags:["POV", "Babe", "Beauty"], status:"published", flagged:false },
    { id:81, title:"Pool Vibes Babes ()", creator:"c1", type:"ugc", category:"Amateur", categories:["Amateur"], views:10353, likes:199, dislikes:3, comments:0, favorites:0, duration:"0:10", uploaded:"2026-01-23", src:"../media/new bunny uplode/Pool vibes babes (more in description) by jennawhoretega on DeviantArt (1).mp4", tags:["Pool", "Amateur", "Babe"], status:"published", flagged:false },
    { id:82, title:"Pool Vibes Babes", creator:"c2", type:"ugc", category:"Amateur", categories:["Amateur"], views:12705, likes:277, dislikes:9, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-22", src:"../media/new bunny uplode/Pool vibes babes more in description by jennawhoretega on Devian (1).mp4", tags:["Babe", "Pool", "Amateur"], status:"published", flagged:false },
    { id:83, title:"Pool Vibes Babes", creator:"c4", type:"ugc", category:"Amateur", categories:["Amateur"], views:10837, likes:182, dislikes:14, comments:4, favorites:0, duration:"0:10", uploaded:"2026-01-27", src:"../media/new bunny uplode/Pool vibes babes more in description by jennawhoretega on Devian.mp4", tags:["Babe", "Pool", "Amateur"], status:"published", flagged:false },
    { id:84, title:"Puria20", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:13264, likes:284, dislikes:16, comments:2, favorites:0, duration:"0:10", uploaded:"2026-06-27", src:"../media/new bunny uplode/Puria20 by NeonRabbitAI on DeviantArt (1).mp4", tags:["Amateur", "POV", "AI"], status:"published", flagged:false },
    { id:85, title:"Puria20", creator:"c3", type:"ugc", category:"AI", categories:["AI"], views:11195, likes:155, dislikes:4, comments:2, favorites:0, duration:"0:10", uploaded:"2026-05-11", src:"../media/new bunny uplode/Puria20 by NeonRabbitAI on DeviantArt.mp4", tags:["AI", "Amateur", "Babe"], status:"published", flagged:false },
    { id:86, title:"Sexy", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12572, likes:182, dislikes:6, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-26", src:"../media/new bunny uplode/Sexy by HotGirls3 on DeviantArt (1).mp4", tags:["Babe", "Lesbian", "Girl Girl"], status:"published", flagged:false },
    { id:87, title:"Sexy", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:11107, likes:256, dislikes:15, comments:1, favorites:0, duration:"0:10", uploaded:"2026-04-02", src:"../media/new bunny uplode/Sexy by HotGirls3 on DeviantArt (2).mp4", tags:["Girl Girl", "Lesbian", "Babe"], status:"published", flagged:true },
    { id:88, title:"Sexy", creator:"c3", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12504, likes:115, dislikes:4, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-15", src:"../media/new bunny uplode/Sexy by HotGirls3 on DeviantArt (3).mp4", tags:["Lesbian", "Girl Girl", "Babe"], status:"published", flagged:false },
    { id:89, title:"Sexy", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:11864, likes:297, dislikes:2, comments:3, favorites:0, duration:"0:10", uploaded:"2026-05-07", src:"../media/new bunny uplode/Sexy by HotGirls3 on DeviantArt (4).mp4", tags:["Girl Girl", "Lesbian", "Babe"], status:"published", flagged:false },
    { id:90, title:"Sexy", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:14771, likes:128, dislikes:10, comments:4, favorites:0, duration:"0:10", uploaded:"2026-05-27", src:"../media/new bunny uplode/Sexy by HotGirls3 on DeviantArt (5).mp4", tags:["Lesbian", "Girl Girl", "Babe"], status:"published", flagged:false },
    { id:91, title:"Sexy", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:11854, likes:167, dislikes:7, comments:1, favorites:0, duration:"0:10", uploaded:"2026-05-23", src:"../media/new bunny uplode/Sexy by HotGirls3 on DeviantArt (6).mp4", tags:["Lesbian", "Girl Girl", "Babe"], status:"published", flagged:false },
    { id:92, title:"Sexy", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:13617, likes:191, dislikes:7, comments:4, favorites:0, duration:"0:10", uploaded:"2026-05-02", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (1).mp4", tags:["Babe", "Girl Girl", "Lesbian"], status:"published", flagged:false },
    { id:93, title:"Sexy", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12111, likes:172, dislikes:10, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-22", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (10).mp4", tags:["Girl Girl", "Babe", "Lesbian"], status:"published", flagged:true },
    { id:94, title:"Sexy", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:10991, likes:262, dislikes:4, comments:0, favorites:0, duration:"0:10", uploaded:"2026-02-24", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (11).mp4", tags:["Girl Girl", "Lesbian", "Babe"], status:"published", flagged:false },
    { id:95, title:"Sexy", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12349, likes:142, dislikes:15, comments:0, favorites:0, duration:"0:10", uploaded:"2026-04-23", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (12).mp4", tags:["Babe", "Girl Girl", "Lesbian"], status:"published", flagged:false },
    { id:96, title:"Sexy", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:10683, likes:151, dislikes:14, comments:3, favorites:0, duration:"0:10", uploaded:"2026-04-25", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (14).mp4", tags:["Babe", "Lesbian", "Girl Girl"], status:"published", flagged:true },
    { id:97, title:"Sexy", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12371, likes:261, dislikes:8, comments:2, favorites:0, duration:"0:10", uploaded:"2026-03-06", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (15).mp4", tags:["Babe", "Lesbian", "Girl Girl"], status:"published", flagged:false },
    { id:98, title:"Sexy", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:11792, likes:283, dislikes:4, comments:3, favorites:0, duration:"0:10", uploaded:"2026-02-09", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (16).mp4", tags:["Babe", "Lesbian", "Girl Girl"], status:"published", flagged:false },
    { id:99, title:"Sexy", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:13262, likes:271, dislikes:3, comments:2, favorites:0, duration:"0:10", uploaded:"2026-05-25", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (17).mp4", tags:["Babe", "Lesbian", "Girl Girl"], status:"published", flagged:false },
    { id:100, title:"Sexy", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:13988, likes:229, dislikes:11, comments:3, favorites:0, duration:"0:10", uploaded:"2026-01-09", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (18).mp4", tags:["Lesbian", "Girl Girl", "Babe"], status:"published", flagged:false },
    { id:101, title:"Sexy", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12377, likes:169, dislikes:8, comments:2, favorites:0, duration:"0:10", uploaded:"2026-01-20", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (19).mp4", tags:["Babe", "Girl Girl", "Lesbian"], status:"published", flagged:false },
    { id:102, title:"Sexy", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:11267, likes:233, dislikes:3, comments:2, favorites:0, duration:"0:10", uploaded:"2026-04-23", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (20).mp4", tags:["Girl Girl", "Babe", "Lesbian"], status:"published", flagged:false },
    { id:103, title:"Sexy", creator:"c3", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:14543, likes:245, dislikes:17, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-07", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (21).mp4", tags:["Girl Girl", "Babe", "Lesbian"], status:"published", flagged:false },
    { id:104, title:"Sexy", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:13738, likes:164, dislikes:19, comments:4, favorites:0, duration:"0:10", uploaded:"2026-06-10", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (22).mp4", tags:["Babe", "Girl Girl", "Lesbian"], status:"published", flagged:false },
    { id:105, title:"Sexy", creator:"c3", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:11845, likes:113, dislikes:14, comments:1, favorites:0, duration:"0:10", uploaded:"2026-06-18", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (23).mp4", tags:["Lesbian", "Babe", "Girl Girl"], status:"published", flagged:false },
    { id:106, title:"Sexy", creator:"c3", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12622, likes:201, dislikes:14, comments:3, favorites:0, duration:"0:10", uploaded:"2026-02-19", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (24).mp4", tags:["Lesbian", "Babe", "Girl Girl"], status:"published", flagged:false },
    { id:107, title:"Sexy", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:13317, likes:272, dislikes:20, comments:3, favorites:0, duration:"0:10", uploaded:"2026-03-19", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (25).mp4", tags:["Girl Girl", "Lesbian", "Babe"], status:"published", flagged:false },
    { id:108, title:"Sexy", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:10441, likes:238, dislikes:13, comments:0, favorites:0, duration:"0:10", uploaded:"2026-04-27", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (26).mp4", tags:["Babe", "Lesbian", "Girl Girl"], status:"published", flagged:true },
    { id:109, title:"Sexy", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:11956, likes:245, dislikes:3, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-20", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (27).mp4", tags:["Lesbian", "Girl Girl", "Babe"], status:"published", flagged:false },
    { id:110, title:"Sexy", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:10764, likes:260, dislikes:15, comments:2, favorites:0, duration:"0:10", uploaded:"2026-01-20", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (6).mp4", tags:["Babe", "Girl Girl", "Lesbian"], status:"published", flagged:true },
    { id:111, title:"Sexy", creator:"c3", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12512, likes:292, dislikes:12, comments:3, favorites:0, duration:"0:10", uploaded:"2026-04-18", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (7).mp4", tags:["Babe", "Girl Girl", "Lesbian"], status:"published", flagged:false },
    { id:112, title:"Sexy", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:14416, likes:204, dislikes:15, comments:1, favorites:0, duration:"0:10", uploaded:"2026-01-23", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (8).mp4", tags:["Lesbian", "Girl Girl", "Babe"], status:"published", flagged:false },
    { id:113, title:"Sexy", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:13726, likes:282, dislikes:9, comments:0, favorites:0, duration:"0:10", uploaded:"2026-01-24", src:"../media/new bunny uplode/Sexy by SexyGirls2 on DeviantArt (9).mp4", tags:["Babe", "Girl Girl", "Lesbian"], status:"published", flagged:false },
    { id:114, title:"Video Compilation Of Hard Fucking", creator:"c1", type:"ugc", category:"Squirt", categories:["Squirt"], views:10018, likes:184, dislikes:15, comments:1, favorites:0, duration:"0:10", uploaded:"2026-06-22", src:"../media/new bunny uplode/VIDEO COMPILATION OF HARD FUCKING by SquirtNatali on DeviantArt (1).mp4", tags:["Compilation", "Amateur", "Squirt"], status:"published", flagged:false },
    { id:115, title:"Video Compilation Of Hard Fucking", creator:"c1", type:"ugc", category:"Squirt", categories:["Squirt"], views:11246, likes:115, dislikes:11, comments:2, favorites:0, duration:"0:10", uploaded:"2026-01-20", src:"../media/new bunny uplode/VIDEO COMPILATION OF HARD FUCKING by SquirtNatali on DeviantArt (2).mp4", tags:["Compilation", "Squirt", "Amateur"], status:"published", flagged:false },
    { id:116, title:"Video Compilation Of Hard Fucking", creator:"c4", type:"ugc", category:"Squirt", categories:["Squirt"], views:14651, likes:102, dislikes:15, comments:0, favorites:0, duration:"0:10", uploaded:"2026-03-21", src:"../media/new bunny uplode/VIDEO COMPILATION OF HARD FUCKING by SquirtNatali on DeviantArt (3).mp4", tags:["Compilation", "Amateur", "Squirt"], status:"published", flagged:false },
    { id:117, title:"Video Compilation Of Hard Fucking", creator:"c1", type:"ugc", category:"Squirt", categories:["Squirt"], views:10875, likes:135, dislikes:12, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-10", src:"../media/new bunny uplode/VIDEO COMPILATION OF HARD FUCKING by SquirtNatali on DeviantArt (4).mp4", tags:["Squirt", "Amateur", "Compilation"], status:"published", flagged:false },
    { id:118, title:"Video Compilation Of Hard Fucking", creator:"c2", type:"ugc", category:"Squirt", categories:["Squirt"], views:13329, likes:181, dislikes:19, comments:4, favorites:0, duration:"0:10", uploaded:"2026-04-25", src:"../media/new bunny uplode/VIDEO COMPILATION OF HARD FUCKING by SquirtNatali on DeviantArt (5).mp4", tags:["Squirt", "Compilation", "Amateur"], status:"published", flagged:false },
    { id:119, title:"Video Compilation Of Hard Fucking", creator:"c2", type:"ugc", category:"Squirt", categories:["Squirt"], views:13190, likes:233, dislikes:5, comments:4, favorites:0, duration:"0:10", uploaded:"2026-06-26", src:"../media/new bunny uplode/VIDEO COMPILATION OF HARD FUCKING by SquirtNatali on DeviantArt.mp4", tags:["Compilation", "Squirt", "Amateur"], status:"published", flagged:false },
    { id:120, title:"Video Girls", creator:"c2", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:10769, likes:156, dislikes:5, comments:3, favorites:0, duration:"0:10", uploaded:"2026-03-25", src:"../media/new bunny uplode/Video Girls Right-click on VIDEO and Loop by JennaJamesXXX on De.mp4", tags:["Girl Girl", "Lesbian", "Babe"], status:"published", flagged:false },
    { id:121, title:"Video Glistening Beauty", creator:"c1", type:"ugc", category:"Blond", categories:["Blond"], views:13212, likes:200, dislikes:20, comments:4, favorites:0, duration:"0:10", uploaded:"2026-02-11", src:"../media/new bunny uplode/Video Glistening Beauty by BlondCrown on DeviantArt.mp4", tags:["Blond", "Babe", "Amateur"], status:"published", flagged:true },
    { id:122, title:"Video Sofia Dirty Talk", creator:"c3", type:"ugc", category:"POV", categories:["POV"], views:11976, likes:150, dislikes:14, comments:0, favorites:0, duration:"0:10", uploaded:"2026-04-27", src:"../media/new bunny uplode/Video Sofia dirty talk by Picknikker on DeviantArt.mp4", tags:["POV", "Dirty Talk", "Amateur"], status:"published", flagged:true },
    { id:123, title:"Video Vikki Sexy Girl", creator:"c4", type:"ugc", category:"Babe", categories:["Babe"], views:12156, likes:249, dislikes:2, comments:2, favorites:0, duration:"0:10", uploaded:"2026-01-26", src:"../media/new bunny uplode/Video Vikki sexy girl by Picknikker on DeviantArt (1).mp4", tags:["POV", "Beauty", "Babe"], status:"published", flagged:false },
    { id:124, title:"Video Vikki Sexy Girl", creator:"c1", type:"ugc", category:"Babe", categories:["Babe"], views:11600, likes:231, dislikes:9, comments:1, favorites:0, duration:"0:10", uploaded:"2026-05-21", src:"../media/new bunny uplode/Video Vikki sexy girl by Picknikker on DeviantArt (2).mp4", tags:["Babe", "Amateur", "POV"], status:"published", flagged:false },
    { id:125, title:"Video Vikki Sexy Girl", creator:"c3", type:"ugc", category:"Babe", categories:["Babe"], views:13094, likes:268, dislikes:18, comments:3, favorites:0, duration:"0:10", uploaded:"2026-06-23", src:"../media/new bunny uplode/Video Vikki sexy girl by Picknikker on DeviantArt (3).mp4", tags:["Babe", "Amateur", "Beauty"], status:"published", flagged:false },
    { id:126, title:"Viva17", creator:"c2", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12716, likes:207, dislikes:4, comments:4, favorites:0, duration:"0:10", uploaded:"2026-06-17", src:"../media/new bunny uplode/Viva17 by BubbleButtAI on DeviantArt (1).mp4", tags:["Booty", "Twerk", "Curvy"], status:"published", flagged:false },
    { id:127, title:"Viva17", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:11646, likes:225, dislikes:3, comments:2, favorites:0, duration:"0:10", uploaded:"2026-05-03", src:"../media/new bunny uplode/Viva17 by BubbleButtAI on DeviantArt (2).mp4", tags:["Twerk", "Booty", "Curvy"], status:"published", flagged:false },
    { id:128, title:"Viva17", creator:"c2", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:10375, likes:109, dislikes:10, comments:2, favorites:0, duration:"0:10", uploaded:"2026-02-04", src:"../media/new bunny uplode/Viva17 by BubbleButtAI on DeviantArt (3).mp4", tags:["Twerk", "Curvy", "Big Ass"], status:"published", flagged:true },
    { id:129, title:"Woman Of Grok", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:10962, likes:217, dislikes:17, comments:2, favorites:0, duration:"0:10", uploaded:"2026-03-07", src:"../media/new bunny uplode/Woman of Grok by Brit-25 on DeviantArt (2).mp4", tags:["POV", "Babe", "AI"], status:"published", flagged:false },
    { id:130, title:"Woman Of Grok", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:11210, likes:290, dislikes:10, comments:1, favorites:0, duration:"0:10", uploaded:"2026-05-14", src:"../media/new bunny uplode/Woman of Grok by Brit-25 on DeviantArt (4).mp4", tags:["Babe", "Amateur", "POV"], status:"published", flagged:false },
    { id:131, title:"Your Ai Girlfriend Wants You To Touch Her Ass", creator:"c2", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:11565, likes:114, dislikes:4, comments:1, favorites:0, duration:"0:10", uploaded:"2026-01-28", src:"../media/new bunny uplode/Your AI girlfriend wants you to touch her ass by Realpalindrome (10).mp4", tags:["Curvy", "Booty", "Big Ass"], status:"published", flagged:false },
    { id:132, title:"Your Ai Girlfriend Wants You To Touch Her Ass", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:14671, likes:269, dislikes:4, comments:3, favorites:0, duration:"0:10", uploaded:"2026-06-20", src:"../media/new bunny uplode/Your AI girlfriend wants you to touch her ass by Realpalindrome (3).mp4", tags:["Twerk", "Big Ass", "Curvy"], status:"published", flagged:false },
    { id:133, title:"Your Ai Girlfriend Wants You To Touch Her Ass", creator:"c1", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12234, likes:296, dislikes:10, comments:3, favorites:0, duration:"0:10", uploaded:"2026-05-13", src:"../media/new bunny uplode/Your AI girlfriend wants you to touch her ass by Realpalindrome (5).mp4", tags:["Twerk", "Curvy", "Big Ass"], status:"published", flagged:false },
    { id:134, title:"Your Ai Girlfriend Wants You To Touch Her Ass", creator:"c2", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:10419, likes:214, dislikes:12, comments:1, favorites:0, duration:"0:10", uploaded:"2026-05-05", src:"../media/new bunny uplode/Your AI girlfriend wants you to touch her ass by Realpalindrome (6).mp4", tags:["Booty", "Curvy", "Big Ass"], status:"published", flagged:false },
    { id:135, title:"Your Ai Girlfriend Wants You To Touch Her Ass", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:13140, likes:157, dislikes:19, comments:4, favorites:0, duration:"0:10", uploaded:"2026-01-26", src:"../media/new bunny uplode/Your AI girlfriend wants you to touch her ass by Realpalindrome (7).mp4", tags:["Big Ass", "Booty", "Curvy"], status:"published", flagged:false },
    { id:136, title:"Your Ai Girlfriend Wants You To Touch Her Ass", creator:"c1", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12583, likes:163, dislikes:2, comments:1, favorites:0, duration:"0:10", uploaded:"2026-04-01", src:"../media/new bunny uplode/Your AI girlfriend wants you to touch her ass by Realpalindrome (8).mp4", tags:["Curvy", "Big Ass", "Booty"], status:"published", flagged:false },
    { id:137, title:"Your Ai Girlfriend Wants You To Touch Her Ass", creator:"c2", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12544, likes:240, dislikes:4, comments:2, favorites:0, duration:"0:10", uploaded:"2026-05-07", src:"../media/new bunny uplode/Your AI girlfriend wants you to touch her ass by Realpalindrome (9).mp4", tags:["Twerk", "Big Ass", "Booty"], status:"published", flagged:false },
    { id:138, title:"Zemba11", creator:"c3", type:"ugc", category:"AI", categories:["AI"], views:11823, likes:147, dislikes:15, comments:0, favorites:0, duration:"0:10", uploaded:"2026-06-01", src:"../media/new bunny uplode/Zemba11 by NeonRabbitAI on DeviantArt (1).mp4", tags:["Amateur", "AI", "POV"], status:"published", flagged:true },
    { id:139, title:"Zemba11", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:12119, likes:222, dislikes:10, comments:4, favorites:0, duration:"0:10", uploaded:"2026-04-21", src:"../media/new bunny uplode/Zemba11 by NeonRabbitAI on DeviantArt (2).mp4", tags:["AI", "POV", "Amateur"], status:"published", flagged:false },
    { id:140, title:"Zemba11", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:14932, likes:287, dislikes:18, comments:0, favorites:0, duration:"0:10", uploaded:"2026-01-08", src:"../media/new bunny uplode/Zemba11 by NeonRabbitAI on DeviantArt (3).mp4", tags:["POV", "AI", "Amateur"], status:"published", flagged:false },
    { id:141, title:"Zemba11", creator:"c3", type:"ugc", category:"AI", categories:["AI"], views:12157, likes:138, dislikes:4, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-22", src:"../media/new bunny uplode/Zemba11 by NeonRabbitAI on DeviantArt (4).mp4", tags:["Amateur", "POV", "Babe"], status:"published", flagged:false },
    { id:142, title:"Zemba11", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:11478, likes:160, dislikes:8, comments:2, favorites:0, duration:"0:10", uploaded:"2026-05-18", src:"../media/new bunny uplode/Zemba11 by NeonRabbitAI on DeviantArt.mp4", tags:["Amateur", "AI", "Babe"], status:"published", flagged:false },
    { id:143, title:"Plastic Bimbo Shows Off Her Skills", creator:"c2", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:10164, likes:251, dislikes:5, comments:4, favorites:0, duration:"0:10", uploaded:"2026-06-10", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt (1).mp4", tags:["Curvy", "Booty", "Big Ass"], status:"published", flagged:false },
    { id:144, title:"Plastic Bimbo Shows Off Her Skills", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:14265, likes:141, dislikes:12, comments:3, favorites:0, duration:"0:10", uploaded:"2026-06-19", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt (2).mp4", tags:["Curvy", "Big Ass", "Twerk"], status:"published", flagged:false },
    { id:145, title:"Plastic Bimbo Shows Off Her Skills", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:13493, likes:231, dislikes:10, comments:3, favorites:0, duration:"0:10", uploaded:"2026-06-04", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt (3).mp4", tags:["Booty", "Twerk", "Big Ass"], status:"published", flagged:false },
    { id:146, title:"Plastic Bimbo Shows Off Her Skills", creator:"c2", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:10936, likes:201, dislikes:10, comments:4, favorites:0, duration:"0:10", uploaded:"2026-02-02", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt (4).mp4", tags:["Big Ass", "Booty", "Twerk"], status:"published", flagged:false },
    { id:147, title:"Plastic Bimbo Shows Off Her Skills", creator:"c3", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12439, likes:188, dislikes:18, comments:1, favorites:0, duration:"0:10", uploaded:"2026-05-06", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt (6).mp4", tags:["Curvy", "Big Ass", "Booty"], status:"published", flagged:false },
    { id:148, title:"Plastic Bimbo Shows Off Her Skills", creator:"c3", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12511, likes:204, dislikes:12, comments:3, favorites:0, duration:"0:10", uploaded:"2026-02-19", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt (7).mp4", tags:["Curvy", "Big Ass", "Booty"], status:"published", flagged:false },
    { id:149, title:"Plastic Bimbo Shows Off Her Skills", creator:"c4", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:12514, likes:204, dislikes:2, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-26", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt (8).mp4", tags:["Booty", "Curvy", "Big Ass"], status:"published", flagged:false },
    { id:150, title:"Plastic Bimbo Shows Off Her Skills", creator:"c3", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:13101, likes:143, dislikes:3, comments:3, favorites:0, duration:"0:10", uploaded:"2026-03-03", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt (9).mp4", tags:["Curvy", "Big Ass", "Twerk"], status:"published", flagged:false },
    { id:151, title:"Plastic Bimbo Shows Off Her Skills", creator:"c3", type:"ugc", category:"Big Ass", categories:["Big Ass"], views:13993, likes:144, dislikes:13, comments:0, favorites:0, duration:"0:10", uploaded:"2026-03-19", src:"../media/new bunny uplode/plastic bimbo shows off her skills by bubblebutty on DeviantArt.mp4", tags:["Booty", "Twerk", "Curvy"], status:"published", flagged:false },
    { id:152, title:"Ai Girlfriend", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:11500, likes:256, dislikes:6, comments:2, favorites:0, duration:"0:10", uploaded:"2026-01-08", src:"../media/new bunny uplode/video-06d357d4.mp4", tags:["Babe", "AI", "POV"], status:"published", flagged:true },
    { id:153, title:"Ai Girlfriend", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:10474, likes:128, dislikes:20, comments:1, favorites:0, duration:"0:10", uploaded:"2026-03-11", src:"../media/new bunny uplode/video-1303188c.mp4", tags:["Amateur", "POV", "AI"], status:"published", flagged:false },
    { id:154, title:"Virtual Vixen", creator:"c4", type:"ugc", category:"AI", categories:["AI"], views:11301, likes:118, dislikes:13, comments:1, favorites:0, duration:"0:10", uploaded:"2026-02-19", src:"../media/new bunny uplode/video-1f21f668.mp4", tags:["Babe", "POV", "Amateur"], status:"published", flagged:false },
    { id:155, title:"Generated Goddess", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:10660, likes:281, dislikes:14, comments:4, favorites:0, duration:"0:10", uploaded:"2026-04-10", src:"../media/new bunny uplode/video-1fea8d98.mp4", tags:["Babe", "POV", "AI"], status:"published", flagged:false },
    { id:156, title:"Virtual Vixen", creator:"c3", type:"ugc", category:"AI", categories:["AI"], views:10889, likes:244, dislikes:5, comments:4, favorites:0, duration:"0:10", uploaded:"2026-06-26", src:"../media/new bunny uplode/video-23078209.mp4", tags:["AI", "Babe", "Amateur"], status:"published", flagged:false },
    { id:157, title:"Ai Girlfriend", creator:"c3", type:"ugc", category:"AI", categories:["AI"], views:13852, likes:220, dislikes:4, comments:2, favorites:0, duration:"0:10", uploaded:"2026-06-19", src:"../media/new bunny uplode/video-25ed2e78.mp4", tags:["AI", "Babe", "Amateur"], status:"published", flagged:false },
    { id:158, title:"Virtual Vixen", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:11551, likes:145, dislikes:14, comments:3, favorites:0, duration:"0:10", uploaded:"2026-03-13", src:"../media/new bunny uplode/video-288708f2.mp4", tags:["POV", "Amateur", "Babe"], status:"published", flagged:false },
    { id:159, title:"Virtual Vixen", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:14673, likes:126, dislikes:12, comments:4, favorites:0, duration:"0:10", uploaded:"2026-01-23", src:"../media/new bunny uplode/video-49006e4b.mp4", tags:["Babe", "POV", "Amateur"], status:"published", flagged:false },
    { id:160, title:"Ai Beauty", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:11479, likes:241, dislikes:6, comments:4, favorites:0, duration:"0:10", uploaded:"2026-05-10", src:"../media/new bunny uplode/video-53e6aa48.mp4", tags:["Amateur", "Babe", "AI"], status:"published", flagged:false },
    { id:161, title:"Virtual Vixen", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:11111, likes:205, dislikes:6, comments:3, favorites:0, duration:"0:10", uploaded:"2026-04-24", src:"../media/new bunny uplode/video-65cb846b.mp4", tags:["POV", "AI", "Babe"], status:"published", flagged:true },
    { id:162, title:"Virtual Vixen", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:11841, likes:128, dislikes:6, comments:0, favorites:0, duration:"0:10", uploaded:"2026-03-18", src:"../media/new bunny uplode/video-68eb7970.mp4", tags:["POV", "Babe", "AI"], status:"published", flagged:false },
    { id:163, title:"Generated Goddess", creator:"c3", type:"ugc", category:"AI", categories:["AI"], views:10253, likes:138, dislikes:8, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-07", src:"../media/new bunny uplode/video-6cfe7080.mp4", tags:["AI", "POV", "Amateur"], status:"published", flagged:false },
    { id:164, title:"Generated Goddess", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:13915, likes:157, dislikes:16, comments:3, favorites:0, duration:"0:10", uploaded:"2026-01-15", src:"../media/new bunny uplode/video-92cbf14e.mp4", tags:["Babe", "AI", "Amateur"], status:"published", flagged:false },
    { id:165, title:"Ai Girlfriend", creator:"c4", type:"ugc", category:"AI", categories:["AI"], views:11401, likes:116, dislikes:14, comments:4, favorites:0, duration:"0:10", uploaded:"2026-06-27", src:"../media/new bunny uplode/video-9f3ace4a.mp4", tags:["AI", "POV", "Amateur"], status:"published", flagged:false },
    { id:166, title:"Virtual Vixen", creator:"c4", type:"ugc", category:"AI", categories:["AI"], views:12794, likes:136, dislikes:7, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-12", src:"../media/new bunny uplode/video-a5579d3f.mp4", tags:["POV", "Amateur", "Babe"], status:"published", flagged:false },
    { id:167, title:"Ai Girlfriend", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:13931, likes:229, dislikes:14, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-09", src:"../media/new bunny uplode/video-a6fd2405.mp4", tags:["Babe", "AI", "POV"], status:"published", flagged:false },
    { id:168, title:"Ai Beauty", creator:"c3", type:"ugc", category:"AI", categories:["AI"], views:13282, likes:237, dislikes:15, comments:2, favorites:0, duration:"0:10", uploaded:"2026-05-22", src:"../media/new bunny uplode/video-a7d2473d.mp4", tags:["AI", "Babe", "POV"], status:"published", flagged:false },
    { id:169, title:"Ai Beauty", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:10748, likes:147, dislikes:8, comments:0, favorites:0, duration:"0:10", uploaded:"2026-05-14", src:"../media/new bunny uplode/video-b5386ff0.mp4", tags:["Babe", "POV", "Amateur"], status:"published", flagged:false },
    { id:170, title:"Virtual Vixen", creator:"c4", type:"ugc", category:"AI", categories:["AI"], views:12040, likes:108, dislikes:3, comments:0, favorites:0, duration:"0:10", uploaded:"2026-03-10", src:"../media/new bunny uplode/video-cd305604.mp4", tags:["POV", "AI", "Amateur"], status:"published", flagged:false },
    { id:171, title:"Virtual Vixen", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:13040, likes:214, dislikes:16, comments:4, favorites:0, duration:"0:10", uploaded:"2026-03-03", src:"../media/new bunny uplode/video-e3750f82.mp4", tags:["POV", "Babe", "AI"], status:"published", flagged:true },
    { id:172, title:"Ai Girlfriend", creator:"c1", type:"ugc", category:"AI", categories:["AI"], views:13753, likes:280, dislikes:4, comments:2, favorites:0, duration:"0:10", uploaded:"2026-06-15", src:"../media/new bunny uplode/video-ec8bc159.mp4", tags:["Babe", "POV", "AI"], status:"published", flagged:false },
    { id:173, title:"Ai Girlfriend", creator:"c4", type:"ugc", category:"AI", categories:["AI"], views:12055, likes:262, dislikes:15, comments:1, favorites:0, duration:"0:10", uploaded:"2026-01-11", src:"../media/new bunny uplode/video-fa6f8c3e.mp4", tags:["AI", "Amateur", "Babe"], status:"published", flagged:false },
    { id:174, title:"Ai Beauty", creator:"c2", type:"ugc", category:"AI", categories:["AI"], views:14674, likes:297, dislikes:5, comments:3, favorites:0, duration:"0:10", uploaded:"2026-03-06", src:"../media/new bunny uplode/video-fdda174a.mp4", tags:["Babe", "Amateur", "POV"], status:"published", flagged:false },
    { id:175, title:"Virtual Vixen", creator:"c4", type:"ugc", category:"AI", categories:["AI"], views:11997, likes:234, dislikes:12, comments:4, favorites:0, duration:"0:10", uploaded:"2026-01-11", src:"../media/new bunny uplode/video-ffa7e3bb.mp4", tags:["AI", "Babe", "Amateur"], status:"published", flagged:false },
    { id:176, title:"Woman And Girls", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:13731, likes:146, dislikes:19, comments:4, favorites:0, duration:"0:10", uploaded:"2026-02-16", src:"../media/new bunny uplode/woman and girls by Belapho on DeviantArt (1).mp4", tags:["Lesbian", "Girl Girl", "Babe"], status:"published", flagged:false },
    { id:177, title:"Woman And Girls", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:13500, likes:168, dislikes:10, comments:0, favorites:0, duration:"0:10", uploaded:"2026-02-10", src:"../media/new bunny uplode/woman and girls by Belapho on DeviantArt.mp4", tags:["Babe", "Lesbian", "Girl Girl"], status:"published", flagged:false },
    { id:178, title:"World Of Sluts", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:14075, likes:281, dislikes:8, comments:3, favorites:0, duration:"0:10", uploaded:"2026-03-10", src:"../media/new bunny uplode/world of sluts by talia666 on DeviantArt (1).mp4", tags:["Lesbian", "Babe", "Girl Girl"], status:"published", flagged:false },
    { id:179, title:"World Of Sluts", creator:"c4", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:11455, likes:195, dislikes:12, comments:0, favorites:0, duration:"0:10", uploaded:"2026-06-11", src:"../media/new bunny uplode/world of sluts by talia666 on DeviantArt (2).mp4", tags:["Girl Girl", "Babe", "Lesbian"], status:"published", flagged:false },
    { id:180, title:"World Of Sluts", creator:"c1", type:"ugc", category:"Girl Girl", categories:["Girl Girl"], views:12269, likes:218, dislikes:18, comments:4, favorites:0, duration:"0:10", uploaded:"2026-06-18", src:"../media/new bunny uplode/world of sluts by talia666 on DeviantArt.mp4", tags:["Lesbian", "Babe", "Girl Girl"], status:"published", flagged:false },
  ],

  comments: [
    { id:"m1", video:1, user:"Maya Chen",  text:"This is incredible quality!", time:"2h" },
    { id:"m2", video:1, user:"DevTalks",   text:"Loved the pacing on this one.", time:"5h" },
    { id:"m3", video:1, user:"Alex",       text:"House Originals never miss.", time:"1d" },
    { id:"m4", video:2, user:"Alex",       text:"Great vibe 🎵", time:"3h" },
    { id:"m5", video:3, user:"Maya Chen",  text:"spam link here buy now", time:"1h", flagged:true },
  ],

  revenue: { total:18420, ads:7200, premium:6100, subscriptions:3400, tips:920, affiliate:800,
    history:[ {m:"Jan",v:9200},{m:"Feb",v:10100},{m:"Mar",v:11800},{m:"Apr",v:13400},{m:"May",v:15600},{m:"Jun",v:18420} ] },

  analytics: {
    views7d:[4200,5100,4800,6300,7100,6800,8200],
    retention:[100,82,71,63,55,49,44,41,38,36],
    countries:[ {c:"United States",p:38},{c:"India",p:14},{c:"Germany",p:9},{c:"Brazil",p:7},{c:"France",p:6},{c:"Other",p:26} ],
    devices:[ {c:"Mobile",p:58},{c:"Desktop",p:31},{c:"TV",p:8},{c:"Tablet",p:3} ],
    traffic:[ {c:"Recommendations",p:44},{c:"Search",p:22},{c:"External",p:16},{c:"Direct",p:11},{c:"Channels",p:7} ],
  },

  system: {
    dau:84200, mau:1240000, uptime:"99.98%", uploadsToday:312,
    moderationQueue:14, storageTB:48.2, processingQueue:6, errors:3,
    bandwidthTB:128, cdnCost:4120,
  },

  users: [
    { id:"u1", name:"Alex", email:"alex@mail.com", role:"creator", status:"active", subs:"Premium", joined:"2025-11-02" },
    { id:"u2", name:"Maya Chen", email:"maya@mail.com", role:"creator", status:"active", subs:"Premium", joined:"2025-09-14" },
    { id:"u3", name:"Sam Rivera", email:"sam@mail.com", role:"viewer", status:"suspended", subs:"Free", joined:"2026-01-20" },
    { id:"u4", name:"Jordan Lee", email:"jordan@mail.com", role:"viewer", status:"active", subs:"Premium", joined:"2026-03-05" },
    { id:"u5", name:"Casey Kim", email:"casey@mail.com", role:"viewer", status:"banned", subs:"Free", joined:"2026-02-11" },
  ],

  flags: [
    { key:"new_homepage", desc:"New homepage layout A/B test", on:true, rollout:50 },
    { key:"ai_thumbnails", desc:"AI thumbnail generation", on:true, rollout:100 },
    { key:"live_streaming", desc:"Creator live streaming", on:false, rollout:0 },
    { key:"watch_parties", desc:"Synchronized watch parties", on:false, rollout:10 },
    { key:"short_form_feed", desc:"Vertical short-form feed", on:true, rollout:25 },
  ],

  moderation: {
    classes:[ {c:"NSFW",n:18},{c:"Violence",n:4},{c:"Spam",n:23},{c:"Copyright",n:7},{c:"Hate Speech",n:2},{c:"Deepfake",n:1},{c:"Fake Engagement",n:11} ],
  },
};
