import { resolve } from "node:path";
import { readdirSync, existsSync } from "node:fs";
import { defineConfig } from "vite";
import dotenv from "dotenv";

dotenv.config();

// `vercel build` (used by .github/workflows/deploy.yml instead of Vercel's
// native git integration — see CLAUDE.md) runs `vercel pull` first, which
// writes the dashboard's env vars to .vercel/.env.production.local, but does
// NOT export them into process.env for the generic build command (vite
// build) it shells out to — that auto-injection only happens for framework
// builds Vercel drives itself. Load that file explicitly so those values
// reach process.env before the `define` block below reads them. (Root cause
// of a real outage: SUPABASE_URL/SUPABASE_KEY were also marked "Sensitive"
// in Vercel, which additionally strips their value from every `vercel pull`
// output entirely — fixed by re-adding them as non-sensitive. Without both
// fixes they built in as empty strings, so SH_API_ENABLED was false in
// production and every view/like/comment persistence call silently
// no-op'd — see streamhub-api.js.)
dotenv.config({ path: resolve(__dirname, ".vercel/.env.production.local") });

// blog/<slug>.html files are generated by scripts/gen-blog-posts.js (run
// before `vite build`, see package.json). Discover them dynamically since
// the post count grows over time.
const blogDir = resolve(__dirname, "blog");
const blogPostInputs = existsSync(blogDir)
  ? Object.fromEntries(
      readdirSync(blogDir)
        .filter((f) => f.endsWith(".html") && f !== "index.html")
        .map((f) => [`blog-${f.replace(/\.html$/, "")}`, resolve(blogDir, f)])
    )
  : {};

const pornstarsDir = resolve(__dirname, "pornstars");
const pornstarInputs = existsSync(pornstarsDir)
  ? Object.fromEntries(
      readdirSync(pornstarsDir)
        .filter((f) => f.endsWith(".html"))
        .map((f) => [`pornstars-${f.replace(/\.html$/, "")}`, resolve(pornstarsDir, f)])
    )
  : {};

const categoriesDir = resolve(__dirname, "categories");
const categoryInputs = existsSync(categoriesDir)
  ? Object.fromEntries(
      readdirSync(categoriesDir)
        .filter((f) => f.endsWith(".html"))
        .map((f) => [`categories-${f.replace(/\.html$/, "")}`, resolve(categoriesDir, f)])
    )
  : {};

const videoDir = resolve(__dirname, "video");
const videoInputs = existsSync(videoDir)
  ? Object.fromEntries(
      readdirSync(videoDir)
        .filter((f) => f.endsWith(".html"))
        .map((f) => [`video-${f.replace(/\.html$/, "")}`, resolve(videoDir, f)])
    )
  : {};

export default defineConfig({
  root: ".",
  define: {
    "process.env.SUPABASE_URL": JSON.stringify(process.env.SUPABASE_URL),
    "process.env.SUPABASE_KEY": JSON.stringify(process.env.SUPABASE_KEY || process.env.SUPABASE_ANON_KEY),
  },
  build: {
    rollupOptions: {
      input: {
        index: resolve(__dirname, "index.html"),
        choose: resolve(__dirname, "choose.html"),
        creator: resolve(__dirname, "creator/index.html"),
        manager: resolve(__dirname, "manager/index.html"),
        viewer: resolve(__dirname, "viewer/index.html"),
        legalTerms: resolve(__dirname, "legal/terms.html"),
        legalPrivacy: resolve(__dirname, "legal/privacy.html"),
        legalDmca: resolve(__dirname, "legal/dmca.html"),
        legal2257: resolve(__dirname, "legal/2257.html"),
        blogIndex: resolve(__dirname, "blog/index.html"),
        ...blogPostInputs,
        ...pornstarInputs,
        ...categoryInputs,
        ...videoInputs,
      },
      output: {
        // Split the huge catalog data (500+ videos) into its own chunk.
        // This allows better caching, parallel loading, and keeps main app chunks smaller.
        manualChunks(id) {
          // The full video list is ONLY reached via a dynamic import() from
          // catalog.js. Give it its own chunk (not the catch-all 'shared' bucket
          // below, which also holds statically-imported modules and would drag
          // this 1.9 MB payload into the entry's eager modulepreload graph).
          // On its own it stays a lazy async chunk, fetched after first paint.
          if (id.includes('/shared/catalog-videos.js')) {
            return 'catalog-videos';
          }
          // Keep taxonomy in the same chunk as catalog.js — catalog's DATA
          // references taxonomy's CATEGORIES at module-init time, so splitting
          // them across chunks causes a cross-chunk temporal-dead-zone error.
          if (id.includes('/shared/catalog.js') || id.includes('/shared/taxonomy.js')) {
            return 'catalog-data';
          }
          if (id.includes('/shared/streamhub-api.js')) {
            return 'streamhub-api';
          }
          // legal.css is its own standalone <link> entry point for the four
          // legal/*.html pages only — it must NOT land in this bucket. Every
          // other /shared/ module funneled into 'shared' gets its CSS merged
          // into one shared-*.css file that index.html also loads (Vite merges
          // CSS per JS chunk name), which was leaking legal.css's body{padding:
          // 40px 20px} (meant to center the legal pages' narrow text column)
          // into the main app's global <body>, pushing the whole sidebar/topbar
          // down and right on every page.
          if (id.includes('/shared/') && !id.endsWith('.css')) {
            return 'shared';
          }
        },
      },
    },
  },
});
