/* Canonical public URLs. Hash aliases must redirect here — never keep both. */

export function slugifySegment(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Category landings generated by scripts/gen-static-routes.js */
export const PUBLIC_CATEGORY_NAMES = [
  "Blonde", "Latina", "Big Ass", "Big Tits", "MILF", "Amateur",
  "Anal", "Blowjob", "POV", "Redhead", "Ebony", "Asian", "Babe",
  "Lesbian", "Creampie",
];

const PUBLIC_CATEGORY_SLUGS = new Set(PUBLIC_CATEGORY_NAMES.map(slugifySegment));

export const PORNSTARS_PATH = "/pornstars/";

export function categoryPagePath(name) {
  const slug = slugifySegment(name);
  if (!slug || !PUBLIC_CATEGORY_SLUGS.has(slug)) return null;
  return `/categories/${slug}.html`;
}

/** In-app Home browse for a category (not the SEO landing). */
export function categoryBrowseHash(name) {
  return "browse/" + encodeURIComponent(name);
}

export function homeFilterHref(filter) {
  if (filter === "pornstars") return PORNSTARS_PATH;
  if (filter === "movies" || filter === "scenes" || filter === "clips") return "/#" + filter;
  return "/";
}
