-- Supabase Database Schema Migration for Video Catalog & Creators
-- Created: 2026-09-02

-- 1. Create videos table
CREATE TABLE IF NOT EXISTS public.videos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    creator_id TEXT REFERENCES public.creators(id) ON DELETE SET NULL,
    category TEXT NOT NULL DEFAULT 'Babe',
    categories TEXT[] DEFAULT ARRAY['Babe']::TEXT[],
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],
    src TEXT NOT NULL,
    thumb TEXT,
    duration TEXT DEFAULT '0:15',
    orientation TEXT DEFAULT 'landscape',
    views BIGINT DEFAULT 1200,
    likes INT DEFAULT 0,
    dislikes INT DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'published',
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create creators table
CREATE TABLE IF NOT EXISTS public.creators (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    handle TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    kind TEXT NOT NULL DEFAULT 'creator',
    bio TEXT,
    avatar TEXT,
    banner TEXT,
    subs INT DEFAULT 0,
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Indexes for high-performance querying
CREATE INDEX IF NOT EXISTS idx_videos_status ON public.videos(status);
CREATE INDEX IF NOT EXISTS idx_videos_category ON public.videos(category);
CREATE INDEX IF NOT EXISTS idx_videos_uploaded_at ON public.videos(uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_videos_orientation ON public.videos(orientation);

-- 4. Row-Level Security (RLS) policies
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creators ENABLE ROW LEVEL SECURITY;

-- Allow public read access to published videos and creators
CREATE POLICY "Public read access for published videos" 
    ON public.videos FOR SELECT 
    USING (status = 'published');

CREATE POLICY "Public read access for creators" 
    ON public.creators FOR SELECT 
    USING (true);
